---

- name: Applying Common Tasks
  become: true
  hosts: zookeeper
  roles:
    - common
    - common-jdk

- name: Installing Zookeeper
  gather_facts: true
  become: true
  hosts: zookeeper
  roles:
    - zookeeper-install
